import "./globals.css";
import Link from "next/link";
import LoginButton from "@/app/loginButton";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import RegisterButton from "@/app/registerButton";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);
  console.log(session === null ? "hello" : session);
  return (
    <html lang="en">
      <body>
        <div className="navbar">
          <Link href="/" className="logo">
            Appleforum
          </Link>
          <Link href="/list">List</Link>
          <Link href="/write">Write</Link>
          <LoginButton session={session} />
          {session === null ? <RegisterButton /> : <></>}
          <span>
            {session === null
              ? "hello"
              : "Welcome, " + session.user.name + "!!  "}
          </span>
        </div>
        {children}
      </body>
    </html>
  );
}
